In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [76]:
data=pd.read_csv("winedata.csv")

In [77]:
data

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0        1    14.23        1.71  2.43               15.6        127   
1        1    13.20        1.78  2.14               11.2        100   
2        1    13.16        2.36  2.67               18.6        101   
3        1    14.37        1.95  2.50               16.8        113   
4        1    13.24        2.59  2.87               21.0        118   
..     ...      ...         ...   ...                ...        ...   
173      3    13.71        5.65  2.45               20.5         95   
174      3    13.40        3.91  2.48               23.0        102   
175      3    13.27        4.28  2.26               20.0        120   
176      3    13.17        2.59  2.37               20.0        120   
177      3    14.13        4.10  2.74               24.5         96   

     Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0             2.80        3.06                  0.28             2.29   
1             2.65        2.76                  0.26             1.28   
2             2.80        3.24                  0.30             2.81   
3             3.85        3.49                  0.24             2.18   
4             2.80        2.69                  0.39             1.82   
..             ...         ...                   ...              ...   
173           1.68        0.61                  0.52             1.06   
174           1.80        0.75                  0.43             1.41   
175           1.59        0.69                  0.43             1.35   
176           1.65        0.68                  0.53             1.46   
177           2.05        0.76                  0.56             1.35   

     Color intensity   Hue  diluted wines  Proline      
0               5.64  1.04           3.92         1065  
1               4.38  1.05           3.40         1050  
2               5.68  1.03           3.17         1185  
3               7.80  0.86           3.45         1480  
4               4.32  1.04           2.93          735  
..               ...   ...            ...          ...  
173             7.70  0.64           1.74          740  
174             7.30  0.70           1.56          750  
175            10.20  0.59           1.56          835  
176             9.30  0.60           1.62          840  
177             9.20  0.61           1.60          560  

[178 rows x 14 columns]

In [78]:
data.isnull().sum()

Class                   0
Alcohol                 0
Malic acid              0
Ash                     0
Alcalinity of ash       0
Magnesium               0
Total phenols           0
Flavanoids              0
Nonflavanoid phenols    0
Proanthocyanins         0
Color intensity         0
Hue                     0
diluted wines           0
Proline                 0
dtype: int64

In [79]:
data.dtypes

Class                     int64
Alcohol                 float64
Malic acid              float64
Ash                     float64
Alcalinity of ash       float64
Magnesium                 int64
Total phenols           float64
Flavanoids              float64
Nonflavanoid phenols    float64
Proanthocyanins         float64
Color intensity         float64
Hue                     float64
diluted wines           float64
Proline                   int64
dtype: object

In [80]:
data.describe()

Class     Alcohol  Malic acid         Ash  Alcalinity of ash  \
count  178.000000  178.000000  178.000000  178.000000         178.000000   
mean     1.938202   13.000618    2.336348    2.366517          19.494944   
std      0.775035    0.811827    1.117146    0.274344           3.339564   
min      1.000000   11.030000    0.740000    1.360000          10.600000   
25%      1.000000   12.362500    1.602500    2.210000          17.200000   
50%      2.000000   13.050000    1.865000    2.360000          19.500000   
75%      3.000000   13.677500    3.082500    2.557500          21.500000   
max      3.000000   14.830000    5.800000    3.230000          30.000000   

        Magnesium  Total phenols  Flavanoids  Nonflavanoid phenols  \
count  178.000000     178.000000  178.000000            178.000000   
mean    99.741573       2.295112    2.029270              0.361854   
std     14.282484       0.625851    0.998859              0.124453   
min     70.000000       0.980000    0.340000              0.130000   
25%     88.000000       1.742500    1.205000              0.270000   
50%     98.000000       2.355000    2.135000              0.340000   
75%    107.000000       2.800000    2.875000              0.437500   
max    162.000000       3.880000    5.080000              0.660000   

       Proanthocyanins  Color intensity         Hue  diluted wines  \
count       178.000000       178.000000  178.000000     178.000000   
mean          1.590899         5.058090    0.957449       2.611685   
std           0.572359         2.318286    0.228572       0.709990   
min           0.410000         1.280000    0.480000       1.270000   
25%           1.250000         3.220000    0.782500       1.937500   
50%           1.555000         4.690000    0.965000       2.780000   
75%           1.950000         6.200000    1.120000       3.170000   
max           3.580000        13.000000    1.710000       4.000000   

       Proline      
count   178.000000  
mean    746.893258  
std     314.907474  
min     278.000000  
25%     500.500000  
50%     673.500000  
75%     985.000000  
max    1680.000000

In [81]:
data.drop('Total phenols',axis=1,inplace=True)

In [82]:
data.drop('Flavanoids',axis=1,inplace=True)

In [83]:
data.drop('diluted wines',axis=1,inplace=True)

In [84]:
data.shape

(178, 11)

In [85]:
from scipy.stats import zscore
zscore=abs(zscore(data))
print(data.shape)
data_new=data.loc[(zscore<3).all(axis=1)]
print(data_new.shape)

(178, 11)
(168, 11)


In [86]:
data_new.skew()

Class                   0.117053
Alcohol                -0.028038
Malic acid              0.966253
Ash                    -0.250438
Alcalinity of ash       0.104774
Magnesium               0.566522
Nonflavanoid phenols    0.481810
Proanthocyanins         0.360217
Color intensity         0.732580
Hue                    -0.137430
Proline                 0.744773
dtype: float64

In [87]:
data_new.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  Proline      
0                  0.28             2.29             5.64  1.04         1065  
1                  0.26             1.28             4.38  1.05         1050  
2                  0.30             2.81             5.68  1.03         1185  
3                  0.24             2.18             7.80  0.86         1480  
4                  0.39             1.82             4.32  1.04          735

In [88]:
ds=data_new

In [89]:
ds.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  Proline      
0                  0.28             2.29             5.64  1.04         1065  
1                  0.26             1.28             4.38  1.05         1050  
2                  0.30             2.81             5.68  1.03         1185  
3                  0.24             2.18             7.80  0.86         1480  
4                  0.39             1.82             4.32  1.04          735

In [90]:
x=ds.iloc[:,1:12]

In [91]:
x.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0    14.23        1.71  2.43               15.6        127   
1    13.20        1.78  2.14               11.2        100   
2    13.16        2.36  2.67               18.6        101   
3    14.37        1.95  2.50               16.8        113   
4    13.24        2.59  2.87               21.0        118   

   Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  Proline      
0                  0.28             2.29             5.64  1.04         1065  
1                  0.26             1.28             4.38  1.05         1050  
2                  0.30             2.81             5.68  1.03         1185  
3                  0.24             2.18             7.80  0.86         1480  
4                  0.39             1.82             4.32  1.04          735

In [92]:
y=ds.iloc[:,0]

In [93]:
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Class, Length: 168, dtype: int64

In [94]:
pd.DataFrame(data=x)

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      14.23        1.71  2.43               15.6        127   
1      13.20        1.78  2.14               11.2        100   
2      13.16        2.36  2.67               18.6        101   
3      14.37        1.95  2.50               16.8        113   
4      13.24        2.59  2.87               21.0        118   
..       ...         ...   ...                ...        ...   
173    13.71        5.65  2.45               20.5         95   
174    13.40        3.91  2.48               23.0        102   
175    13.27        4.28  2.26               20.0        120   
176    13.17        2.59  2.37               20.0        120   
177    14.13        4.10  2.74               24.5         96   

     Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  Proline      
0                    0.28             2.29             5.64  1.04         1065  
1                    0.26             1.28             4.38  1.05         1050  
2                    0.30             2.81             5.68  1.03         1185  
3                    0.24             2.18             7.80  0.86         1480  
4                    0.39             1.82             4.32  1.04          735  
..                    ...              ...              ...   ...          ...  
173                  0.52             1.06             7.70  0.64          740  
174                  0.43             1.41             7.30  0.70          750  
175                  0.43             1.35            10.20  0.59          835  
176                  0.53             1.46             9.30  0.60          840  
177                  0.56             1.35             9.20  0.61          560  

[168 rows x 10 columns]

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
max_acc_score=0
for r_state in range(42,101):
    x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=r_state,test_size=0.33)
    lg=LogisticRegression()
    lg.fit(x_train,y_train)
    y_pred=lg.predict(x_test)
    acc_score=accuracy_score(y_test,y_pred)
    print("accuracy_score:",r_state,"is",acc_score)
    if acc_score>max_acc_score:
        max_acc_score=acc_score
        final_r_state=r_state
        
print(final_r_state)
print(max_acc_score)

accuracy_score: 42 is 0.9464285714285714
accuracy_score: 43 is 0.9821428571428571
accuracy_score: 44 is 1.0
accuracy_score: 45 is 0.9642857142857143
accuracy_score: 46 is 0.8928571428571429
accuracy_score: 47 is 0.8928571428571429
accuracy_score: 48 is 0.9107142857142857
accuracy_score: 49 is 0.9642857142857143
accuracy_score: 50 is 0.9642857142857143
accuracy_score: 51 is 0.875
accuracy_score: 52 is 0.9464285714285714
accuracy_score: 53 is 0.9107142857142857
accuracy_score: 54 is 0.9285714285714286
accuracy_score: 55 is 0.9642857142857143
accuracy_score: 56 is 0.9107142857142857
accuracy_score: 57 is 0.9464285714285714
accuracy_score: 58 is 0.8928571428571429
accuracy_score: 59 is 0.9821428571428571
accuracy_score: 60 is 0.875
accuracy_score: 61 is 0.9642857142857143
accuracy_score: 62 is 0.9642857142857143
accuracy_score: 63 is 0.8928571428571429
accuracy_score: 64 is 0.9464285714285714
accuracy_score: 65 is 0.9642857142857143
accuracy_score: 66 is 0.9642857142857143
accuracy_score: 

In [100]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.33,random_state=44)

In [101]:
lg=LogisticRegression()
lg.fit(x_train,y_train)
pred=lg.predict(x_test)
print(pred)

[1 3 1 1 2 3 2 3 3 2 3 3 3 2 1 2 1 2 1 3 1 1 1 2 2 3 2 3 1 1 2 2 2 1 2 2 1
 1 1 2 3 1 3 3 2 2 2 3 2 2 3 2 2 1 1 2]


In [102]:
print("accuracy_score:",accuracy_score(y_test,pred))
print("confusion_matrix:",confusion_matrix(y_test,pred))
print("classification_report:",classification_report(y_test,pred))

accuracy_score: 1.0
confusion_matrix: [[18  0  0]
 [ 0 23  0]
 [ 0  0 15]]
classification_report:               precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        15

    accuracy                           1.00        56
   macro avg       1.00      1.00      1.00        56
weighted avg       1.00      1.00      1.00        56



In [99]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print(accuracy_score(predmnb,y_test))
print(confusion_matrix(y_test,predmnb))
print(classification_report(y_test,predmnb))

0.8392857142857143
[[19  0  1]
 [ 1 18  2]
 [ 3  2 10]]
              precision    recall  f1-score   support

           1       0.83      0.95      0.88        20
           2       0.90      0.86      0.88        21
           3       0.77      0.67      0.71        15

    accuracy                           0.84        56
   macro avg       0.83      0.82      0.83        56
weighted avg       0.84      0.84      0.84        56



In [103]:
from sklearn.svm import SVC
def svmkernel(ker):
    svc=SVC(kernel=ker)
    svc.fit(x_train,y_train)
    predsvc=svc.predict(x_test)
    print(accuracy_score(predsvc,y_test))
    print(confusion_matrix(y_test,predsvc))
    print(classification_report(y_test,predsvc))

In [104]:
svmkernel('linear')

1.0
[[18  0  0]
 [ 0 23  0]
 [ 0  0 15]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        15

    accuracy                           1.00        56
   macro avg       1.00      1.00      1.00        56
weighted avg       1.00      1.00      1.00        56



In [105]:
svmkernel('rbf')

0.8392857142857143
[[18  0  0]
 [ 0 22  1]
 [ 0  8  7]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       0.73      0.96      0.83        23
           3       0.88      0.47      0.61        15

    accuracy                           0.84        56
   macro avg       0.87      0.81      0.81        56
weighted avg       0.86      0.84      0.83        56



In [106]:
svmkernel('poly')

0.7678571428571429
[[18  0  0]
 [ 0 23  0]
 [ 0 13  2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       0.64      1.00      0.78        23
           3       1.00      0.13      0.24        15

    accuracy                           0.77        56
   macro avg       0.88      0.71      0.67        56
weighted avg       0.85      0.77      0.70        56



In [107]:
from sklearn.tree import DecisionTreeClassifier
dct=DecisionTreeClassifier()
dct.fit(x_train,y_train)
preddtc=dct.predict(x_test)
print(accuracy_score(preddtc,y_test))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

0.9642857142857143
[[17  1  0]
 [ 0 22  1]
 [ 0  0 15]]
              precision    recall  f1-score   support

           1       1.00      0.94      0.97        18
           2       0.96      0.96      0.96        23
           3       0.94      1.00      0.97        15

    accuracy                           0.96        56
   macro avg       0.96      0.97      0.97        56
weighted avg       0.97      0.96      0.96        56



In [108]:
from sklearn.neighbors import KNeighborsClassifier
dtn=KNeighborsClassifier()
dtn.fit(x_train,y_train)
preddtn=dtn.predict(x_test)
print(accuracy_score(preddtn,y_test))
print(confusion_matrix(y_test,preddtn))
print(classification_report(y_test,preddtn))

0.625
[[16  2  0]
 [ 0 18  5]
 [ 2 12  1]]
              precision    recall  f1-score   support

           1       0.89      0.89      0.89        18
           2       0.56      0.78      0.65        23
           3       0.17      0.07      0.10        15

    accuracy                           0.62        56
   macro avg       0.54      0.58      0.55        56
weighted avg       0.56      0.62      0.58        56



In [110]:
from sklearn.model_selection import cross_val_score
model=[DecisionTreeClassifier(),SVC(),KNeighborsClassifier(),MultinomialNB(),LogisticRegression()]
for m in model:
    score=cross_val_score(m,x,y,cv=8)
    print(score)
    print(score.mean())
    print(score.std())

[0.85714286 0.76190476 0.85714286 1.         1.         0.80952381
 0.95238095 1.        ]
0.9047619047619048
0.08908708063747481
[0.66666667 0.66666667 0.57142857 0.66666667 0.76190476 0.57142857
 0.9047619  0.85714286]
0.7083333333333333
0.11526736149426837
[0.76190476 0.71428571 0.57142857 0.76190476 0.61904762 0.85714286
 0.71428571 0.76190476]
0.7202380952380952
0.08396866654563025
[0.52380952 0.76190476 0.61904762 0.71428571 0.85714286 0.71428571
 0.95238095 0.95238095]
0.7619047619047619
0.14285714285714282
[0.85714286 0.9047619  0.85714286 0.95238095 1.         0.95238095
 0.95238095 1.        ]
0.9345238095238095
0.05290591915068804


In [111]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
parameters={'kernel':('linear','rbf','poly'),'C':[1,10]}
svc=svm.SVC()
clf=GridSearchCV(svc,parameters)
clf.fit(x_train,y_train)
print(clf.best_score_)
print(clf.best_estimator_.kernel)
print(clf.best_params_)

0.9375494071146246
linear
{'C': 10, 'kernel': 'linear'}


In [112]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
parameters={'criterion':('gini','entropy')}
dtc=DecisionTreeClassifier()
clf=GridSearchCV(dtc,parameters,scoring='accuracy',cv=5)
clf.fit(x_train,y_train)
print(clf.best_score_)
print(clf.best_estimator_.criterion)
print(clf.best_params_)

0.9205533596837945
entropy
{'criterion': 'entropy'}


In [113]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,random_state=45)
rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

1.0
[[18  0  0]
 [ 0 23  0]
 [ 0  0 15]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        23
           3       1.00      1.00      1.00        15

    accuracy                           1.00        56
   macro avg       1.00      1.00      1.00        56
weighted avg       1.00      1.00      1.00        56



In [114]:
from sklearn.ensemble import AdaBoostClassifier
ad=AdaBoostClassifier(n_estimators=50,base_estimator=svc,algorithm='SAMME')
ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print(accuracy_score(y_test,predad))
print(confusion_matrix(y_test,predad))
print(classification_report(y_test,predad))

0.7321428571428571
[[18  0  0]
 [ 0 23  0]
 [ 0 15  0]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        18
           2       0.61      1.00      0.75        23
           3       0.00      0.00      0.00        15

    accuracy                           0.73        56
   macro avg       0.54      0.67      0.58        56
weighted avg       0.57      0.73      0.63        56



In [117]:
from sklearn.model_selection import cross_val_score
model=[DecisionTreeClassifier(),SVC(),KNeighborsClassifier(),MultinomialNB(),LogisticRegression(),RandomForestClassifier()]
for m in model:
    score=cross_val_score(m,x,y,cv=8)
    print(score)
    print(score.mean())
    print(score.std())

[0.76190476 0.76190476 0.9047619  1.         1.         0.9047619
 0.95238095 1.        ]
0.9107142857142856
0.09354900979465305
[0.66666667 0.66666667 0.57142857 0.66666667 0.76190476 0.57142857
 0.9047619  0.85714286]
0.7083333333333333
0.11526736149426837
[0.76190476 0.71428571 0.57142857 0.76190476 0.61904762 0.85714286
 0.71428571 0.76190476]
0.7202380952380952
0.08396866654563025
[0.52380952 0.76190476 0.61904762 0.71428571 0.85714286 0.71428571
 0.95238095 0.95238095]
0.7619047619047619
0.14285714285714282
[0.85714286 0.9047619  0.85714286 0.95238095 1.         0.95238095
 0.95238095 1.        ]
0.9345238095238095
0.05290591915068804
[0.95238095 1.         0.95238095 1.         1.         0.95238095
 1.         1.        ]
0.9821428571428572
0.023053472298853697


In [ ]:
# as per analysis RandomForestClassifier is having high cross_val_score


In [118]:
from sklearn.externals import joblib
joblib.dump(rf,'rf.wine.pkl')

['rf.wine.pkl']